package:
    name: zegami-dependencies
    version: '1.8.6'
source:
    git_url:  https://github.com/zegami/zegami-dependencies.git
build:
    number: '1'
requirements:
    build:
        - yaml 0.1.6 0
        - dotnet-framework 4.5.2 1 # [win]
        - mongodb 3.29 6 # [win]
        - pystache 0.5.4 py35_0
        - python 3.5.2
        - pillow-simd 3.4 py35_0
        - nomkl  0 # [not win]
        - colorama 0.3.7 py35_0
        - jinja2 2.8 py35_1
        - numpy 1.11.1 py35_nomkl_0
        - pip 8.1.2 py35_0
        - pycparser 2.14 py35_1
        - pyparsing 2.1.4 py35_0
        - pytz 2016.4 py35_0
        - requests 2.9.1 py35_0
        - ujson 1.35 py35_0
        - werkzeug 0.11.10 py35_0
        - scandir  py35_0
        - cchardet 1.0.0 py35_0
        - boto 2.43.0 py35_0
        - motor 1.1 py35_0
        - pymongo 3.4.0 py35_0
        - flask 0.11.1 py35_0 # [unix]
        - flask-compress 1.3.0 py35_0 # [not win]
        - flask-cors 2.1.2 py35_0 # [not win]
        - flask 0.10.1 py35_0 # [win]
        - flask-cors 1.10.3 py35_0 # [win]
        - flask-compress 1.3.0 py35_0 # [win]
        - pypyodbc  py35_0
        - ldap3  py35_0
        - boto3  py35_0
        - pynacl  py35_0
        - cffi 1.6.0 py35_0
        - tifffile 0.9.0 np111py35_0
        - blinker 1.4 py35_0
        - nginx 1.12.0 0 # [not win]
        - uwsgi 2.0.12 py35_0 # [not win]
        - unixodbc 2.3.4 0 # [not win]
        - psutil 4.3.0 py35_0 # [win]
        - simple-settings 0.9.0conf2 py35_0
        - dask 0.13.0 py35_0
        - distributed 1.15.1 py35_0
        - wfastcgi 2.2  # [win]
        - raven 6.0.0 py35_0
        - log4mongo 1.6.0 py35_0
        - jsonschema 2.5.1 py35_0
        - xlrd 1.0.0 py35_0
        - pandas 0.18.1 np111py35_0
        - inflection 0.3.1 py35_0
        - libiconv 1.14 0
        - flask-assets 0.12 py35_0
    run:
        - yaml 0.1.6 0
        - dotnet-framework 4.5.2 1 # [win]
        - mongodb 3.29 6 # [win]
        - pystache 0.5.4 py35_0
        - python 3.5.2
        - pillow-simd 3.4 py35_0
        - nomkl  0 # [not win]
        - colorama 0.3.7 py35_0
        - jinja2 2.8 py35_1
        - numpy 1.11.1 py35_nomkl_0
        - pip 8.1.2 py35_0
        - pycparser 2.14 py35_1
        - pyparsing 2.1.4 py35_0
        - pytz 2016.4 py35_0
        - requests 2.9.1 py35_0
        - ujson 1.35 py35_0
        - werkzeug 0.11.10 py35_0
        - scandir  py35_0
        - cchardet 1.0.0 py35_0
        - boto 2.43.0 py35_0
        - motor 1.1 py35_0
        - pymongo 3.4.0 py35_0
        - flask 0.11.1 py35_0 # [unix]
        - flask-compress 1.3.0 py35_0 # [not win]
        - flask-cors 2.1.2 py35_0 # [not win]
        - flask 0.10.1 py35_0 # [win]
        - flask-cors 1.10.3 py35_0 # [win]
        - flask-compress 1.3.0 py35_0 # [win]
        - pypyodbc  py35_0
        - ldap3  py35_0
        - boto3  py35_0
        - pynacl  py35_0
        - cffi 1.6.0 py35_0
        - tifffile 0.9.0 np111py35_0
        - blinker 1.4 py35_0
        - nginx 1.12.0 0 # [not win]
        - uwsgi 2.0.12 py35_0 # [not win]
        - unixodbc 2.3.4 0 # [not win]
        - psutil 4.3.0 py35_0 # [win]
        - simple-settings 0.9.0conf2 py35_0
        - dask 0.13.0 py35_0
        - distributed 1.15.1 py35_0
        - wfastcgi 2.2  # [win]
        - raven 6.0.0 py35_0
        - log4mongo 1.6.0 py35_0
        - jsonschema 2.5.1 py35_0
        - xlrd 1.0.0 py35_0
        - pandas 0.18.1 np111py35_0
        - inflection 0.3.1 py35_0
        - libiconv 1.14 0
        - flask-assets 0.12 py35_0


about:
    home: https://github.com/zegami/zegami-dependencies
    license: MIT
    summary: A package to maintain a list of Zegami dependencies which can be used with commands like conda build, conda env etc.
