package:
    name: zegami-dependencies
    version: '1.8.1'
source:
    git_url:  https://github.com/zegami/zegami-dependencies.git
build:
    number: '1'
requirements:
    build:
        - python 3.5.2
        - pillow-simd 3.4
        - nomkl                            #    [not win]
        - colorama 0.3.7
        - pystache 0.5.4
        - jinja2 2.8
        - numpy 1.11.1
        - pip 8.1.2
        - pycparser 2.14
        - pyparsing 2.1.4
        - pytz 2016.4
        - requests 2.9.1
        - ujson 1.35
        - werkzeug 0.11.10
        - yaml 0.1.6 0
        - scandir
        - cchardet 1.0.0
        - boto 2.43.0
        - motor 1.1
        - pymongo 3.4.0
        - flask 0.11.1                #  [unix]
        - flask-compress 1.3.0      #  [not win]
        - flask-cors 2.1.2          # [not win]
        - flask 0.10.1              #    [win]
        - flask-cors 1.10.3         #    [win]
        - flask-compress 1.3.0      #    [win]
        - pypyodbc
        - ldap3
        - boto3
        - pynacl
        - cffi  1.6.0
        - tifffile  0.9.0
        - blinker  1.4
        - nginx  1.11.4               #                 [not win]
        - uwsgi  2.0.12            #                   [not win]
        - unixodbc  2.3.4              #                  [not win]
        - psutil  4.3.0                 #               [win]
        - simple-settings 0.9.0conf2
        - dask 0.13.0
        - distributed 1.15.1
        - mongodb 3.29 6                 #                  [win]
        - dotnet-framework 4.5.2 1        #                           [win]
        - wfastcgi  2.2                    #            [win]
        - raven  6.0.0
        - log4mongo 1.6.0
        - jsonschema 2.5.1
        - xlrd 1.0.0
        - awesome-slugify 1.6.5
        - pandas 0.18.1
        - inflection 0.3.1

    run:
        - python 3.5.2
        - pillow-simd 3.4
        - nomkl                            #    [not win]
        - colorama 0.3.7
        - pystache 0.5.4
        - jinja2 2.8
        - numpy 1.11.1
        - pip 8.1.2
        - pycparser 2.14
        - pyparsing 2.1.4
        - pytz 2016.4
        - requests 2.9.1
        - ujson 1.35
        - werkzeug 0.11.10
        - yaml 0.1.6 0
        - scandir
        - cchardet 1.0.0
        - boto 2.43.0
        - motor 1.1
        - pymongo 3.4.0
        - flask 0.11.1                #  [unix]
        - flask-compress 1.3.0      #  [not win]
        - flask-cors 2.1.2          # [not win]
        - flask 0.10.1              #    [win]
        - flask-cors 1.10.3         #    [win]
        - flask-compress 1.3.0      #    [win]
        - pypyodbc
        - ldap3
        - boto3
        - pynacl
        - cffi  1.6.0
        - tifffile  0.9.0
        - blinker  1.4
        - nginx  1.11.4               #                 [not win]
        - uwsgi  2.0.12            #                   [not win]
        - unixodbc  2.3.4              #                  [not win]
        - psutil  4.3.0                 #               [win]
        - simple-settings 0.9.0conf2
        - dask 0.13.0
        - distributed 1.15.1
        - mongodb 3.29 6                 #                  [win]
        - dotnet-framework 4.5.2 1        #                           [win]
        - wfastcgi  2.2                    #            [win]
        - raven  6.0.0
        - log4mongo 1.6.0
        - jsonschema 2.5.1
        - xlrd 1.0.0
        - awesome-slugify 1.6.5
        - pandas 0.18.1
        - inflection 0.3.1


about:
    home: https://github.com/zegami/zegami-dependencies
    license: MIT
    summary: A package to maintain a list of Zegami dependencies which can be used with commands like conda build, conda env etc.
